# Generated by Django 5.0 on 2024-01-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnk_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
