# Generated by Django 5.0 on 2024-01-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnk_auth', '0003_customuser_nick_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nick_name',
        ),
    ]
