# Generated by Django 5.0 on 2024-01-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnk_auth', '0005_useraccountdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccountdetails',
            name='created_at',
        ),
    ]
